apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-nginx-deployment
  labels:
    app: app1-nginx-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-nginx-qa
  template:
    metadata:
      labels:
        app: app1-nginx-qa
    spec:
      containers:
        - name: app1-nginx
          image: acrforaksdemo34.azurecr.io/custom2aksnginxapp1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-loadbalancer-service-qa
  labels:
    app: app1-nginx-qa
spec:
  type: ClusterIP
  selector:
    app: app1-nginx-qa
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app1-nginx-qa
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: qa.alpercan.site
    http:
      paths:
      - backend:
          service:
            name: app1-nginx-clusterip-service-qa
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - qa.alpercan.site
      secretName: qa-alpercan-secret    
  


